### ISSUE TITLE
(Jigsaw) Overall Size of game Issue

### ISSUE THREAD

**Issue by Rodolfo-Reynoso** [mristic505/jjflavorsgames#21]
![Screen Shot 2018-01-23 at 5:09 PM](http://marker.screenshots.prod.s3.amazonaws.com/ff0c52216e5b469b939dcf7465423a07-1516727366746.png)

**Summary:** 
Size of the game on an iPad seems much smaller compared to the rest of the games.
**Steps to Reproduce:** 
Launch game in iPad size (768px)
**Expected Results:** 
Game should take up more of the main area
**Actual Results:** 
The game takes up too little of the screen size.
**Notes:**

---
### More Info

**Source URL**: [http://rodolfo.brandconnections.com/jjflavorsgames/?page=jigsaw-puzzle&play=pineapple](http://rodolfo.brandconnections.com/jjflavorsgames/?page=jigsaw-puzzle&play=pineapple)

<table><tr><td><strong>Browser</strong></td><td>Chrome 63.0.3239.132</td></tr><tr><td><strong>Screen Size</strong></td><td>768 x 1024</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.12.5</td></tr><tr><td><strong>Viewport Size</strong></td><td>1916 x 1080</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@2x</td></tr><tr><td><strong>User Agent</strong></td><td>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36</td></tr></table>

**Comment by Milosh911** [comment]
We have a sidebar with puzzle pieces there, so yes: 

![puzzle_bug](https://user-images.githubusercontent.com/17505260/35293089-ec4087b2-0072-11e8-9e23-f7a6245e9de2.PNG)

There is a little bit of space left even with sidebars, but it was done for tehnical reasons, because if there is no space left, it can happen that the piece can "jump" when dragging is initiated, as it is bounded to html container.

**Comment by mristic505** [comment]
We kinda already knew this. Closed
